theme: minimal
plugins:
    - jekyll-relative-links
relative_links:
    enabled: true
    collections: true
include:
    - HarapAlb.md
    - Ion.md
    - MoaraCuNoroc.md
    - OScrisoarePierduta.md
    - ScrisoareaLuiNeacsu.md
    - LICENSE.md
